name: Filmmaker
favicon: null
layout_spectrum: 0
typography_spectrum: 0.78496
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4a0017'
    - '#990831'
    - '#c22540'
    - '#fcb78f'
  brandStrength: 0.7361981319263577
  lightness: 0.6664778916165233
  saturation: 0
  rhythmicContrast: 1
purpose: []
